---
all:
  children:
    linux_hosts:
      hosts:
        devbox.devops.example:
          ansible_host: 192.168.44.11
    macos_hosts:
      hosts:
        kp-comp-mac-01.local:
          ansible_host: 192.168.0.252
