---
# Ansible connection variables for macOS hosts
ansible_connection: ssh
ansible_user: kpsingh

# Roles to be included for macOS hosts
install_nerd_font: true
install_adobe_acrobat_reader: true
install_ghostty: true
install_google_chrome: true
install_google_drive: true
install_visual_studio_code: true
install_zed: true
install_notion: true
install_virtualbox: true
install_vagrant: true
